// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Migrations
{
    [DbContext(typeof(ParksAPIContext))]
    [Migration("20220918115105_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Crater Lake",
                            Type = "National",
                            Year = 1902
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Yellowstone",
                            Type = "National",
                            Year = 1872
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Yosemite",
                            Type = "National",
                            Year = 1890
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Grand Teton",
                            Type = "National",
                            Year = 1950
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Tryon Creek",
                            Type = "State",
                            Year = 1971
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Champoeg",
                            Type = "State",
                            Year = 1913
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Silver Falls",
                            Type = "State",
                            Year = 1933
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
